name: simple_oauth2_server
author: Christophe Hurpeau <christophe@hurpeau.com>
version: 0.0.2
homepage: https://github.com/christophehurpeau/dart-simple_oauth2_server
description: Simple OAuth2 for Google, Facebook and Windows Live, Server-side
documentation: http://christophehurpeau.github.io/dart-simple_oauth2_server/
environment:
  sdk: '>=0.1.1 <2.0.0'
dependencies:
  http: '>= 0.9.2'
