name: simple_oauth2_server
version: 0.0.1
author: Christophe Hurpeau <christophe@hurpeau.com>
description:  Simple OAuth2 for Google, Facebook and Windows Live, Server-side
homepage: https://github.com/christophehurpeau/dart-simple_oauth2_server
documentation: https://github.com/christophehurpeau/dart-simple_oauth2_server/wiki

environment:
  sdk: ">=0.8.10+6 <2.0.0"

dependencies:
  http: '>= 0.9.2'